# Generated by Django 3.0.7 on 2021-03-27 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210327_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
