# Generated by Django 3.0.7 on 2021-03-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210327_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='address',
        ),
        migrations.AddField(
            model_name='customers',
            name='address_1',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='address_2',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
