# Generated by Django 3.0.7 on 2021-03-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210330_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='address_2',
        ),
    ]
